import { certificationsType } from "@/src/types/certifications";
import { IconBrandGoogle, IconBrandMeta } from "@tabler/icons-react";

const certifications: certificationsType = [
  {
    name: "Google AI Essentials",
    issuer: "Google",
    issueDate: "2025-02-20",
    skills: [
      "Innovation",
      "Prompt Engineering",
      "Security Awareness",
      "Data Ethics",
      "Generative AI",
      "Operational Efficiency",
      "Machine Learning",
      "ChatGPT",
      "Artificial Intelligence",
      "Human Machine Interfaces",
      "Content Creation",
      "Brainstorming",
    ],
    icons: {
      issuer: IconBrandGoogle,
    },
  },
  {
    name: "Foundations of Cybersecurity",
    issuer: "Google",
    issueDate: "2025-02-22",
    skills: [
      "Security Management",
      "Cyber Attacks",
      "Data Ethics",
      "Security Controls",
      "Security Information and Event Management (SIEM)",
      "Cyber Security Strategy",
      "Network Analysis",
      "Information Assurance",
      "Cybersecurity",
      "Cyber Risk",
      "Ethical Standards And Conduct",
      "Incident Response",
    ],
    icons: {
      issuer: IconBrandGoogle,
    },
  },
  {
    name: "Introduction to Front-End Development",
    issuer: "Meta",
    issueDate: "2025-02-23",
    skills: [
      "Web Development Tools",
      "React.js",
      "User Interface (UI)",
      "Bootstrap (Front-End Framework)",
      "Front-End Web Development",
      "Web Applications",
      "JavaScript Frameworks",
      "Responsive Web Design",
      "HTML and CSS",
      "Web Design and Development",
      "Javascript",
    ],
    icons: {
      issuer: IconBrandMeta,
    },
  },
  {
    name: "Programming with JavaScript",
    issuer: "Meta",
    issueDate: "2025-02-23",
    skills: [
      "Computer Programming",
      "Unit Testing",
      "Programming Principles",
      "Jest (JavaScript Testing Framework)",
      "Web Applications",
      "Functional Design",
      "JavaScript",
      "Event-Driven Programming",
      "Program Development",
      "Node.JS",
      "Object Oriented Programming (OOP)",
      "Package and Software Management",
    ],
    icons: {
      issuer: IconBrandMeta,
    },
  },
  {
    name: "Version Control",
    issuer: "Meta",
    issueDate: "2025-02-25",
    skills: [
      "Command-Line Interface",
      "Github",
      "Software Development",
      "Unix Commands",
      "Version Control",
      "Linux",
      "Git (Version Control System)",
      "File Management",
      "Web Development",
      "Software Versioning",
      "Software Development Tools",
      "Linux Commands",
    ],
    icons: {
      issuer: IconBrandMeta,
    },
  },
  {
    name: "HTML and CSS in depth",
    issuer: "Meta",
    issueDate: "2025-02-28",
    skills: [
      "Data Validation",
      "Semantic Web",
      "User Interface (UI)",
      "Animations",
      "Debugging",
      "Web Development",
      "Front-End Web Development",
      "Bootstrap (Front-End Framework)",
      "Responsive Web Design",
      "HTML and CSS",
      "JavaScript",
      "Web Content Accessibility Guidelines",
    ],
    icons: {
      issuer: IconBrandMeta,
    },
  },
];

export default certifications;
